name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar estrutura do projeto
        run: |
          test -f site/index.html
          echo "Arquivo index.html encontrado com sucesso."

      - name: Mostrar informações do arquivo
        run: |
          ls -la
          ls -la site
